
const Constants = {
    ADD_TODO: "ADD_TODO",
    EDIT_TODO: "EDIT_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    CLEAR_TODO: "CLEAR_TODO",
    UPDATE_TODO_COUNT: "UPDATE_TODO_COUNT",
    ADD_ERRORS: "ADD_ERRORS",
    REMOVE_ERROS: "REMOVE_ERROS",
    TOGGLE_EDIT_MODE: "TOGGLE_EDIT_MODE",
    SAVED: "SAVED",
    EDITING: "EDITING"
}

export default Constants